# -*- coding: utf-8 -*-
"""TEXT documentation customization.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1vfUqwkEPpyy47zHRc6X9M20tErMJGbu8

**1. Install Libraries**
"""

!pip install --quiet transformers torch scikit-learn pandas

"""**2. Import Libraries**"""

import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import LabelEncoder

import torch
from torch.utils.data import Dataset

from transformers import (
    BertTokenizer,
    BertForSequenceClassification,
    Trainer,
    TrainingArguments
)

import os
os.environ["WANDB_DISABLED"] = "true"  # disable wandb

"""**3. Upload CSV**"""

from google.colab import files
uploaded = files.upload()

import io
csv_file = list(uploaded.keys())[0]
df = pd.read_csv(io.BytesIO(uploaded[csv_file]))
df.head()

"""**4. Data Preprocessing**"""

df = df.dropna()

df['text'] = df['text'].str.lower()

le = LabelEncoder()
df['label'] = le.fit_transform(df['labels'])

"""**5. Train/Test Split**"""

train_texts, test_texts, train_labels, test_labels = train_test_split(
    df['text'].tolist(),
    df['label'].tolist(),
    test_size=0.2,
    random_state=42
)

"""**6. Tokenization + Dataset Class**"""

tokenizer = BertTokenizer.from_pretrained("bert-base-uncased")

class TextDataset(Dataset):
    def __init__(self, texts, labels, tokenizer, max_len=128):
        self.texts = texts
        self.labels = labels
        self.tokenizer = tokenizer
        self.max_len = max_len

    def __len__(self):
        return len(self.texts)

    def __getitem__(self, idx):
        enc = self.tokenizer(
            self.texts[idx],
            truncation=True,
            padding='max_length',
            max_length=self.max_len,
            return_tensors='pt'
        )

        return {
            'input_ids': enc['input_ids'].squeeze(),
            'attention_mask': enc['attention_mask'].squeeze(),
            'labels': torch.tensor(self.labels[idx], dtype=torch.long)
        }

train_dataset = TextDataset(train_texts, train_labels, tokenizer)
test_dataset = TextDataset(test_texts, test_labels, tokenizer)

"""7. Load BERT **Model**"""

model = BertForSequenceClassification.from_pretrained(
    "bert-base-uncased",
    num_labels=len(df['label'].unique())
)

"""**8. Training Arguments**"""

training_args = TrainingArguments(
    output_dir="./results",
    num_train_epochs=2,
    per_device_train_batch_size=8,
    per_device_eval_batch_size=8,
    logging_dir="./logs",
    logging_steps=10,
    eval_strategy="epoch"   # <-- FIXED
)

"""*9. Trainer Setup*"""

trainer = Trainer(
    model=model,
    args=training_args,
    train_dataset=train_dataset,
    eval_dataset=test_dataset
)

"""**10. Train BERT**"""

trainer.train(resume_from_checkpoint=True)

"""**11. Evaluate BERT**"""

metrics = trainer.evaluate()
metrics

"""**12. Save Model + Tokenizer**"""

model.save_pretrained("./saved_model")
tokenizer.save_pretrained("./saved_model")

"""**13. Load Model for Predictions**"""

loaded_tokenizer = BertTokenizer.from_pretrained("./saved_model")
loaded_model = BertForSequenceClassification.from_pretrained("./saved_model")
loaded_model.eval()

"""**14. Prediction Function for NEW Text**"""

import torch

# One-cell interactive demo for new text classification
def classify_text(text):
    """
    Classify a new text using the trained BERT model and show the original label name.
    """
    enc = loaded_tokenizer(
        text,
        return_tensors="pt",
        truncation=True,
        padding="max_length",
        max_length=128
    )
    with torch.no_grad():
        outputs = loaded_model(**enc)

    pred_id = torch.argmax(outputs.logits, dim=1).item()
    return le.inverse_transform([pred_id])[0]

# Interactive input for demo
new_text = input("Enter text to classify: ")
predicted_category = classify_text(new_text)

# Display result
print(f"\nYour text: {new_text}")
print(f"Predicted Category: {predicted_category}")

